version: "3.8"
services:
  simple-test-nodejs-with-docker:
    build: .
    container_name: test-app-container
    ports:
      - "4000:4000"
    command: npm start
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on:
      - simple-test-nodejs-with-docker